### PR TITLE
Allow for angular expressions

### PR DESCRIPTION
**Pull request by mkozono**
First of all, thank you for maintaining this project, I ran it on a large set of files and it worked great for getting everything consistent again (it successfully beautified over 400 files).

However, I had to make a change to get it to not raise an error for a few Angular templates we have.  This change didn't affect the beautifier's behavior on our other ~400 files.

Please let me know if I'm going about this appropriately, I've only ever PR'd typos.  Thanks!

### CODE REVIEW

**Comment by threedaymonk** [comment]
Thanks for this. 65ff462 needed fixing anyway, so I'll cherry-pick that straight away.

You've fixed your specific problem of using `<` in an attribute, but it ought also to be possible to use `>` in a double-quoted string, which will be very difficult with this parser. Maybe it's time to rewrite it with something more robust.

**Comment by threedaymonk** [comment]
I take that back! `ng-show="foo > 1" *does* work.

**Comment by mkozono** [comment]
:) I could have mentioned that that worked without needing a fix

**Comment by threedaymonk** [comment]
Merged in e9fd433. I moved the `ng-show` sample into `behavior_spec.rb` and wrote a couple of specs there instead, as I felt that explained itself a bit better.

Thank you!

**Comment by mkozono** [comment]
Yeah, I was unsure about my change to the test.  I agree that's clearer.  Thanks for getting this in so quickly!

**Comment by threedaymonk** [comment]
Released 1.0.2.

**Pull request closed without merging**
