### PR TITLE
Bundled pr

### PR DESCRIPTION
**Pull request by amcvitty**
This PR bundles some commits that I see are useful from this fork https://github.com/jeremyf/htmlbeautifier . I've added some test cases to show the impact. To review, I suggest you look at each commit individually so you can match the test changes with the code changes.

**Reordering the self-closing tags regex**

This has bitten a few people from what I can see in the issues section. The test is mine, the code change is from [here](https://github.com/jeremyf/htmlbeautifier/commit/b27ac1d9a004e6fc2606331eafeb7ef4c5d79c0b). My summary is that a full solution to parsing javascript, css and html all in one might mean switching from regexes, which would be crazy. In the meantime, this simple change is helpful for a lot of people and not harmful to anyone.

**In foreign blocks (script/style), using totally blank lines instead of indenting the blank lines along with the code**

This is clearly a matter of styling preference, but my observation is that modern editors and style guides tend to suggest removing whitespace from blank lines. for example: this [w3 style guide](https://www.w3.org/wiki/Coding_style#:~:text=Blank%20lines%20should%20be%20precisely%20that%3A%20blank%20lines%20%E2%80%94%20without%20spaces%20nor%20tabs) for javascript

**Fixing a warning for rdoc**

`bundle exec rspec` was showing this warning:
```
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /Volumes/dev/htmlbeautifier/htmlbeautifier.gemspec:13.
```

### CODE REVIEW

**Comment by threedaymonk** [comment]
Thanks. I've already fixed the `rdoc` problem in master, so I'll rebase this and work on it offline.

> My summary is that a full solution to parsing javascript, css and html all in one might mean switching from regexes

That's one reason I haven't touched this for ages! If I were writing this today I'd do it very differently.

I agree with you re the indenting of blank lines.

**Comment by amcvitty** [comment]
Cool thanks. You should find the other commits self-contained and self-explanatory so I hope it’s easy!
________________________________

**Comment by threedaymonk** [comment]
OK, I think that's all merged. I rewrote the blank line spec to make it isolated and more obvious.

Thank you very much!

**Comment by amcvitty** [comment]
Awesome. Thank you!
________________________________

**Pull request closed without merging**
